sudo: required
services:
  - docker
  
before_install:
  - docker build -t lmurali89/react-test -f ./client/Dockerfile.dev ./client
  - docker build myotherproject
  
script:
  - docker run lmurali89/react-test npm test -- --coverage
  
after_success:
  - docker build -t lmurali89/multi-client ./client
  - docker build -t lmurali89/multi-nginx ./nginx
  - docker build -t lmurali89/multi-server ./server
  - docker build -t lmurali89/multi-worker ./worker
  #log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #To push images to docker hub
  - docker push lmurali89/multi-client
  - docker push lmurali89/multi-nginx
  - docker push lmurali89/multi-server
  - docker push lmurali89/multi-worker